language: php

cache:
    directories:
        - $HOME/.composer/cache

env:
    - PHP_CS_FIXER_IGNORE_ENV=true

php:
    - 7.4

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_install:
    - travis_retry composer self-update --no-interaction

install:
    - travis_retry composer update --no-interaction --prefer-dist

script:
    - composer
